"""이벤트 정의 — 티어/체인/캐스케이드 + 강도(severity)/직접 충격(impact) 시스템.

severity: light(가벼운 사건) / medium(중간 위기) / major(큰 위기).
impact  : 이벤트가 그 턴 게이지에 직접 가하는 외생 충격(드리프트/정책과 별개).
          major일수록 크게 때려 "이번 턴 큰일났다"가 느껴지게.
          (게이지에만 적용, ETF 신호엔 안 들어감 — EMH ρ 보호. engine 참조)
choices : v1 잔존 자산(선택지별 base_effects). v2는 카드풀이 대체하나 narration 등에서 참조.
"""

EVENTS = [
    # ══════════════════════════════════════
    # 티어 1 — 초반 (턴 1~7)
    # ══════════════════════════════════════
    {
        "id": "oil_crisis",
        "title": "중동 군사 충돌로 유가 급등",
        "desc": "중동 지역 무력 충돌이 격화되며 국제 유가가 배럴당 $120을 돌파했습니다.",
        "tier": 1,
        "tags": ["energy", "international"],
        "severity": "medium",
        "impact": {"inflation": 7, "tension": 4},
        "chain_to": "oil_aftermath",
        "chain_prob": 0.5,
        "choices": [
            {"label": "전략 비축유 방출",
             "base_effects": {"debt": 5, "inflation": -8, "morale": 3, "tension": -2}, "variance": 2},
            {"label": "긴급 금리 인상 (0.5%p)",
             "base_effects": {"debt": -3, "inflation": -5, "morale": -7, "tension": 0}, "variance": 2},
            {"label": "외교 중재 시도",
             "base_effects": {"debt": 0, "inflation": 2, "morale": 5, "tension": -10}, "variance": 3},
        ],
    },
    {
        "id": "oil_aftermath",
        "title": "유가 위기 후폭풍",
        "desc": "유가 급등 여파로 물류비가 치솟고, 항공·운송업계가 긴급 지원을 요청했습니다.",
        "tier": 1,
        "tags": ["energy", "domestic"],
        "severity": "light",
        "impact": {"inflation": 4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "운송업 긴급 유류세 감면",
             "base_effects": {"debt": 7, "inflation": -4, "morale": 5, "tension": 0}, "variance": 2},
            {"label": "대중교통 확대 투자",
             "base_effects": {"debt": 10, "inflation": -2, "morale": 8, "tension": 0}, "variance": 2},
            {"label": "시장 자율 조정 대기",
             "base_effects": {"debt": 0, "inflation": 5, "morale": -6, "tension": 0}, "variance": 3},
        ],
    },
    {
        "id": "semiconductor",
        "title": "반도체 공급망 위기",
        "desc": "주요 반도체 생산국이 수출 규제를 발표, 글로벌 공급망에 충격이 가해졌습니다.",
        "tier": 1,
        "tags": ["tech", "trade"],
        "severity": "medium",
        "impact": {"inflation": 5, "tension": 4},
        "chain_to": "semiconductor_reshoring",
        "chain_prob": 0.4,
        "choices": [
            {"label": "국내 반도체 산업 긴급 보조금",
             "base_effects": {"debt": 10, "inflation": -3, "morale": 5, "tension": 3}, "variance": 2},
            {"label": "대체 공급국과 긴급 협상",
             "base_effects": {"debt": 3, "inflation": 2, "morale": 0, "tension": -5}, "variance": 2},
            {"label": "수입 관세 보복 조치",
             "base_effects": {"debt": 0, "inflation": 7, "morale": -3, "tension": 8}, "variance": 3},
        ],
    },
    {
        "id": "semiconductor_reshoring",
        "title": "반도체 리쇼어링 결정",
        "desc": "공급망 위기를 계기로 국내 반도체 생산라인 유치 논의가 본격화됐습니다.",
        "tier": 1,
        "tags": ["tech", "domestic"],
        "severity": "light",
        "impact": {"inflation": 3},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "대규모 팹 건설 국비 투자",
             "base_effects": {"debt": 15, "inflation": -2, "morale": 6, "tension": -3}, "variance": 3},
            {"label": "외국 기업 유치 세금 혜택",
             "base_effects": {"debt": 5, "inflation": 0, "morale": 2, "tension": -5}, "variance": 2},
            {"label": "민간 주도 투자 유도",
             "base_effects": {"debt": 2, "inflation": 3, "morale": -2, "tension": 0}, "variance": 2},
        ],
    },
    {
        "id": "natural_disaster",
        "title": "대규모 자연재해 발생",
        "desc": "남부 지방에 역대급 태풍이 상륙, 수조 원의 피해가 예상됩니다.",
        "tier": 1,
        "tags": ["domestic", "crisis"],
        "severity": "medium",
        "impact": {"morale": -6, "debt": 5},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "긴급 재난 지원금 지급",
             "base_effects": {"debt": 12, "inflation": 3, "morale": 10, "tension": 0}, "variance": 3},
            {"label": "민간 보험사 주도 복구",
             "base_effects": {"debt": 2, "inflation": 5, "morale": -8, "tension": 0}, "variance": 2},
            {"label": "국제 원조 요청",
             "base_effects": {"debt": 4, "inflation": 0, "morale": 2, "tension": 5}, "variance": 2},
        ],
    },
    {
        "id": "labor_strike",
        "title": "노동자 총파업 임박",
        "desc": "최저임금 동결에 반발해 주요 산업 노동자들이 총파업을 예고했습니다.",
        "tier": 1,
        "tags": ["domestic", "social"],
        "severity": "medium",
        "impact": {"morale": -7, "inflation": 3},
        "chain_to": "strike_aftermath",
        "chain_prob": 0.5,
        "choices": [
            {"label": "최저임금 15% 인상 수용",
             "base_effects": {"debt": 6, "inflation": 8, "morale": 12, "tension": 0}, "variance": 2},
            {"label": "노사 중재위원회 구성",
             "base_effects": {"debt": 2, "inflation": 2, "morale": 3, "tension": 0}, "variance": 2},
            {"label": "파업 강경 진압",
             "base_effects": {"debt": 0, "inflation": -2, "morale": -15, "tension": 5}, "variance": 3},
        ],
    },
    {
        "id": "strike_aftermath",
        "title": "파업 후속 여파",
        "desc": "노동 분쟁 이후 기업들의 해외 이전 검토 소식이 전해지고 있습니다.",
        "tier": 1,
        "tags": ["domestic", "social"],
        "severity": "light",
        "impact": {"morale": -4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "기업 잔류 인센티브 패키지",
             "base_effects": {"debt": 8, "inflation": -2, "morale": 4, "tension": 0}, "variance": 2},
            {"label": "노동 유연성 법안 추진",
             "base_effects": {"debt": 0, "inflation": -3, "morale": -10, "tension": 0}, "variance": 3},
            {"label": "현상 유지",
             "base_effects": {"debt": 0, "inflation": 3, "morale": -4, "tension": 2}, "variance": 2},
        ],
    },
    {
        "id": "capital_outflow",
        "title": "외국 자본 대규모 이탈",
        "desc": "신용등급 하향 우려로 외국인 투자자들이 대규모 매도에 나섰습니다.",
        "tier": 1,
        "tags": ["finance", "international"],
        "severity": "medium",
        "impact": {"debt": 6, "tension": 5},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "자본 유출 규제 강화",
             "base_effects": {"debt": 0, "inflation": 5, "morale": -5, "tension": 8}, "variance": 2},
            {"label": "기준금리 긴급 인상",
             "base_effects": {"debt": -5, "inflation": -6, "morale": -8, "tension": 0}, "variance": 2},
            {"label": "외환보유고 투입 방어",
             "base_effects": {"debt": 8, "inflation": -4, "morale": 3, "tension": -2}, "variance": 3},
        ],
    },
    {
        "id": "trade_boom",
        "title": "수출 호황 — 무역흑자 사상 최대",
        "desc": "글로벌 수요 급증으로 수출이 전년 대비 25% 증가, 사상 최대 무역흑자를 기록했습니다.",
        "tier": 1,
        "tags": ["trade", "positive"],
        "severity": "light",
        "impact": {"debt": -4, "morale": 4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "흑자 재원으로 국채 상환",
             "base_effects": {"debt": -10, "inflation": 2, "morale": 3, "tension": 0}, "variance": 2},
            {"label": "복지 예산 확대",
             "base_effects": {"debt": 0, "inflation": 4, "morale": 10, "tension": 0}, "variance": 2},
            {"label": "전략 산업 투자 기금 조성",
             "base_effects": {"debt": 3, "inflation": -2, "morale": 5, "tension": -3}, "variance": 2},
        ],
    },
    # ══════════════════════════════════════
    # 티어 2 — 중반 (턴 8~14)
    # ══════════════════════════════════════
    {
        "id": "currency_attack",
        "title": "헤지펀드 통화 공격",
        "desc": "대형 헤지펀드들이 원화 공매도에 나서며 환율이 급등하고 있습니다.",
        "tier": 2,
        "tags": ["finance", "international"],
        "severity": "medium",
        "impact": {"inflation": 6, "debt": 5},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "외환시장 직접 개입",
             "base_effects": {"debt": 8, "inflation": -5, "morale": 3, "tension": 5}, "variance": 3},
            {"label": "자본 이동 임시 제한",
             "base_effects": {"debt": 0, "inflation": 3, "morale": -5, "tension": 10}, "variance": 3},
            {"label": "금리 인상으로 방어",
             "base_effects": {"debt": -3, "inflation": -7, "morale": -10, "tension": 0}, "variance": 3},
        ],
    },
    {
        "id": "housing_bubble",
        "title": "부동산 버블 경고",
        "desc": "주요 도시 주택 가격이 1년 새 40% 급등, 자산 버블 우려가 커지고 있습니다.",
        "tier": 2,
        "tags": ["domestic", "finance"],
        "severity": "medium",
        "impact": {"inflation": 6, "morale": -4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "대출 규제 강화 (LTV/DTI 하향)",
             "base_effects": {"debt": 0, "inflation": -5, "morale": -8, "tension": 0}, "variance": 3},
            {"label": "공공임대주택 대규모 공급",
             "base_effects": {"debt": 12, "inflation": 2, "morale": 7, "tension": 0}, "variance": 3},
            {"label": "보유세 인상",
             "base_effects": {"debt": -5, "inflation": -3, "morale": -6, "tension": 0}, "variance": 3},
        ],
    },
    {
        "id": "pandemic",
        "title": "신종 감염병 확산",
        "desc": "새로운 변이 바이러스가 급속히 확산되며 의료 시스템에 부하가 걸리고 있습니다.",
        "tier": 2,
        "tags": ["domestic", "crisis"],
        "severity": "major",
        "impact": {"morale": -10, "debt": 8},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "전면 봉쇄 + 재난지원금",
             "base_effects": {"debt": 15, "inflation": 5, "morale": -5, "tension": 0}, "variance": 4},
            {"label": "선별 격리 + 의료 증원",
             "base_effects": {"debt": 8, "inflation": 3, "morale": 3, "tension": 0}, "variance": 3},
            {"label": "경제 우선 최소 규제",
             "base_effects": {"debt": 2, "inflation": -2, "morale": -12, "tension": 3}, "variance": 4},
        ],
    },
    {
        "id": "ally_request",
        "title": "동맹국 군사 파병 요청",
        "desc": "주요 동맹국이 분쟁 지역 파병을 공식 요청했습니다. 국내 여론이 분열되고 있습니다.",
        "tier": 2,
        "tags": ["international", "military"],
        "severity": "medium",
        "impact": {"tension": 6, "morale": -4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "파병 수용",
             "base_effects": {"debt": 8, "inflation": 0, "morale": -8, "tension": -12}, "variance": 3},
            {"label": "비전투 지원만 파견",
             "base_effects": {"debt": 4, "inflation": 0, "morale": -3, "tension": -5}, "variance": 2},
            {"label": "파병 거부",
             "base_effects": {"debt": 0, "inflation": 0, "morale": 5, "tension": 10}, "variance": 3},
        ],
    },
    {
        "id": "climate_accord",
        "title": "탄소 감축 국제 압박",
        "desc": "국제 기후 협약에서 2030년까지 탄소 배출 50% 감축 목표가 제시됐습니다.",
        "tier": 2,
        "tags": ["international", "energy"],
        "severity": "medium",
        "impact": {"inflation": 4, "tension": 3},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "적극 수용 — 탄소세 도입",
             "base_effects": {"debt": -3, "inflation": 7, "morale": -5, "tension": -8}, "variance": 3},
            {"label": "단계적 이행 협상",
             "base_effects": {"debt": 2, "inflation": 3, "morale": 2, "tension": -3}, "variance": 2},
            {"label": "이행 유예 요청",
             "base_effects": {"debt": 0, "inflation": -2, "morale": 4, "tension": 6}, "variance": 3},
        ],
    },
    {
        "id": "trade_war",
        "title": "무역 전쟁 본격화",
        "desc": "경쟁국이 주력 수출품에 45% 관세를 부과, 보복 관세 논쟁이 격화됩니다.",
        "tier": 2,
        "tags": ["trade", "international"],
        "severity": "medium",
        "impact": {"inflation": 6, "tension": 6},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "맞대응 보복 관세",
             "base_effects": {"debt": 0, "inflation": 8, "morale": 3, "tension": 12}, "variance": 4},
            {"label": "WTO 제소 + 외교 해결",
             "base_effects": {"debt": 3, "inflation": 3, "morale": 0, "tension": -5}, "variance": 3},
            {"label": "수출 시장 다변화 투자",
             "base_effects": {"debt": 7, "inflation": -2, "morale": 5, "tension": -3}, "variance": 3},
        ],
    },
    # ══════════════════════════════════════
    # 티어 3 — 후반 (턴 15~20)
    # ══════════════════════════════════════
    {
        "id": "credit_downgrade",
        "title": "국가 신용등급 강등",
        "desc": "국제 신용평가사가 국가 신용등급을 한 단계 하향 조정했습니다.",
        "tier": 3,
        "tags": ["finance", "crisis"],
        "severity": "major",
        "impact": {"debt": 12, "morale": -6},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "긴축 재정 패키지 발표",
             "base_effects": {"debt": -8, "inflation": -3, "morale": -12, "tension": 0}, "variance": 4},
            {"label": "경기 부양 + 성장으로 반전",
             "base_effects": {"debt": 10, "inflation": 6, "morale": 5, "tension": 0}, "variance": 5},
            {"label": "IMF 예방적 금융 지원 요청",
             "base_effects": {"debt": 5, "inflation": -5, "morale": -8, "tension": 5}, "variance": 4},
        ],
    },
    {
        "id": "brain_drain",
        "title": "인재 대량 해외 유출",
        "desc": "고급 인력의 해외 이민이 급증, 핵심 산업의 경쟁력 저하 우려가 커지고 있습니다.",
        "tier": 3,
        "tags": ["domestic", "social"],
        "severity": "light",
        "impact": {"morale": -4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "고급 인력 소득세 감면",
             "base_effects": {"debt": 5, "inflation": -2, "morale": 6, "tension": 0}, "variance": 3},
            {"label": "연구·창업 지원 펀드 조성",
             "base_effects": {"debt": 8, "inflation": 0, "morale": 8, "tension": 0}, "variance": 3},
            {"label": "이민 규제 강화",
             "base_effects": {"debt": 0, "inflation": 3, "morale": -10, "tension": 3}, "variance": 4},
        ],
    },
    {
        "id": "nuclear_crisis",
        "title": "한반도 핵 위기 고조",
        "desc": "북방 세력의 핵 실험 강행으로 국제 사회 긴장이 극도로 고조됐습니다.",
        "tier": 3,
        "tags": ["international", "military"],
        "severity": "major",
        "impact": {"tension": 15, "morale": -5},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "군비 증강 + 방위비 확대",
             "base_effects": {"debt": 12, "inflation": 3, "morale": -5, "tension": -8}, "variance": 5},
            {"label": "다자간 외교 중재",
             "base_effects": {"debt": 3, "inflation": 0, "morale": 3, "tension": -5}, "variance": 4},
            {"label": "독자적 핵 억제력 개발 선언",
             "base_effects": {"debt": 15, "inflation": 5, "morale": 8, "tension": 15}, "variance": 5},
        ],
    },
    {
        "id": "global_recession",
        "title": "글로벌 경기 침체",
        "desc": "세계 경제가 동반 침체에 빠지며 수출이 급감하고 금융시장이 요동치고 있습니다.",
        "tier": 3,
        "tags": ["finance", "trade", "crisis"],
        "severity": "major",
        "impact": {"debt": 10, "morale": -8, "inflation": 4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "대규모 재정 부양책",
             "base_effects": {"debt": 15, "inflation": 5, "morale": 8, "tension": 0}, "variance": 5},
            {"label": "구조조정 + 산업 재편",
             "base_effects": {"debt": 5, "inflation": -3, "morale": -10, "tension": 0}, "variance": 4},
            {"label": "통화 완화 (양적 완화)",
             "base_effects": {"debt": 8, "inflation": 10, "morale": 3, "tension": -2}, "variance": 5},
        ],
    },
    # ══════════════════════════════════════
    # 캐스케이드 이벤트 — 게이지 임계값 초과 시 해금
    # ══════════════════════════════════════
    {
        "id": "imf_warning",
        "title": "IMF 재정 건전성 경고",
        "desc": "IMF가 국가 부채 수준에 대해 공식 경고를 발표했습니다. 구조조정 압박이 거세지고 있습니다.",
        "tier": 1,
        "tags": ["cascade_debt", "finance"],
        "severity": "medium",
        "impact": {"debt": 7, "morale": -5},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "IMF 권고안 수용 (긴축)",
             "base_effects": {"debt": -10, "inflation": -5, "morale": -15, "tension": 5}, "variance": 3},
            {"label": "부분 수용 + 자체 계획",
             "base_effects": {"debt": -5, "inflation": -2, "morale": -5, "tension": 2}, "variance": 3},
            {"label": "경고 무시 + 성장 정책",
             "base_effects": {"debt": 5, "inflation": 5, "morale": 8, "tension": 8}, "variance": 4},
        ],
    },
    {
        "id": "street_protests",
        "title": "대규모 시위 발생",
        "desc": "민심 악화로 전국 주요 도시에서 대규모 시위가 발생했습니다. 일부 지역에서 충돌이 보고됩니다.",
        "tier": 1,
        "tags": ["cascade_morale", "social"],
        "severity": "medium",
        "impact": {"morale": -8, "tension": 4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "시위대 요구 수용 + 내각 개편",
             "base_effects": {"debt": 5, "inflation": 3, "morale": 15, "tension": 0}, "variance": 3},
            {"label": "대화 채널 개설 + 일부 양보",
             "base_effects": {"debt": 2, "inflation": 0, "morale": 7, "tension": 0}, "variance": 3},
            {"label": "질서 유지 우선 (강경 대응)",
             "base_effects": {"debt": 0, "inflation": 0, "morale": -10, "tension": 8}, "variance": 4},
        ],
    },
    {
        "id": "bank_run",
        "title": "뱅크런 — 대규모 예금 인출",
        "desc": "인플레이션 공포로 시중 은행에 예금 인출 사태가 발생하고 있습니다.",
        "tier": 1,
        "tags": ["cascade_inflation", "finance"],
        "severity": "major",
        "impact": {"inflation": 12, "morale": -6},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "예금 보호 한도 상향 + 유동성 공급",
             "base_effects": {"debt": 10, "inflation": -5, "morale": 5, "tension": 0}, "variance": 3},
            {"label": "긴급 금리 대폭 인상",
             "base_effects": {"debt": -5, "inflation": -10, "morale": -12, "tension": 0}, "variance": 4},
            {"label": "일시적 인출 한도 설정",
             "base_effects": {"debt": 0, "inflation": -3, "morale": -15, "tension": 5}, "variance": 4},
        ],
    },
    {
        "id": "military_provocation",
        "title": "인접국 군사 도발",
        "desc": "인접국 군함이 영해를 침범, 군사적 긴장이 극도로 높아졌습니다.",
        "tier": 1,
        "tags": ["cascade_tension", "military"],
        "severity": "major",
        "impact": {"tension": 14, "debt": 4},
        "chain_to": None,
        "chain_prob": 0,
        "choices": [
            {"label": "군사력 시위 대응",
             "base_effects": {"debt": 8, "inflation": 3, "morale": 5, "tension": -10}, "variance": 4},
            {"label": "UN 안보리 긴급 소집 요청",
             "base_effects": {"debt": 2, "inflation": 0, "morale": 0, "tension": -5}, "variance": 3},
            {"label": "양자 정상회담 제안",
             "base_effects": {"debt": 0, "inflation": 0, "morale": 3, "tension": -15}, "variance": 5},
        ],
    },
]
